apiVersion: v1
kind: ConfigMap
metadata:
  name: rayls-flagger
data:
  config.json: |
    {
      "Database": {
        "Type": "postgresql",
        "ConnectionString": "host=postgresql user=postgres password=postgres dbname=raylsdb port=5432"
      },
      "CommitChain": {
         "URL": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "PLStorage": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "TokenRegistry": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "PrivateKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "ChainId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "DHPublic": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "DHSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "StartingBlock": xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,
         "OperatorChainId": "999",
         "BatchSize": "20"
       },
      "Logging": "development"
    }