{{- if .Values.privacyLedger.ingress.enabled }}
{{- $releaseName := .Release.Name}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-ingress
  labels:
    {{- include "privacy-ledger.labels" . | nindent 4 }}
    project: {{ .Values.global.project.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- with .Values.privacyLedger.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.privacyLedger.ingress.className }}
  ingressClassName: {{ .Values.privacyLedger.ingress.className }}
  {{- end }}
  {{- if .Values.privacyLedger.ingress.tls }}
  tls:
    {{- range .Values.privacyLedger.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.privacyLedger.ingress.hosts }}
    - host: {{ tpl .host $ }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: "{{ $releaseName }}-svc"
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}