{{- if .Values.circomApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-circomapi-svc
  labels:
    app: {{ .Release.Name }}-circomapi-svc
    project: {{ .Values.global.project.name }}
spec:
  type: {{ .Values.circomApi.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.circomApi.service.port }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}-circomapi
{{- end }}