{{- if .Values.relayer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kmm-svc
  labels:
    app: {{ .Release.Name }}-kmm-svc
    project: {{ .Values.global.project.name }}
spec:
  type: {{ .Values.kmm.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.kmm.service.port }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}-kmm
{{- end }}