{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relayer.serviceAccountName" . }}
  labels:
    {{- include "relayer.labels" . | nindent 4 }}
    project: {{ .Values.global.project.name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
