apiVersion: v1
kind: Service
metadata:
  name: rayls-privacy-ledger
spec:
  type: ClusterIP
  ports:
    - name: p8545
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: p8660
      protocol: TCP
      port: 8660
      targetPort: 8660
    - name: metrics
      port: 6060
      protocol: TCP
      targetPort: 6060
  selector:
    app: rayls-privacy-ledger