#!/bin/bash

set -a
source .env
set +a

setup_config(){
mkdir -p ./rayls
mkdir -p ./rayls/relayer/var

cat <<EOF > ./rayls/relayer/var/.env

BLOCKCHAIN_DATABASE_NAME=rayls-relayer
BLOCKCHAIN_DATABASE_CONNECTIONSTRING="mongodb://mongodb:27017/admin?directConnection=true&replicaSet=rs0"
BLOCKCHAIN_DATABASE_TYPE=mongodb
BLOCKCHAIN_KMS_OPERATION_SERVICE_ROOT_URL=http://kmm:8083
BLOCKCHAIN_CHAINURL=http://privacy-ledger:8545
BLOCKCHAIN_CHAINID=${NODE_PL_CHAIN_ID}
BLOCKCHAIN_PLSTARTINGBLOCK=${BLOCKCHAIN_PLSTARTINGBLOCK}
BLOCKCHAIN_EXECUTOR_BATCH_MESSAGES=${BLOCKCHAIN_EXECUTOR_BATCH_MESSAGES}
BLOCKCHAIN_PLENDPOINTADDRESS=${BLOCKCHAIN_PLENDPOINTADDRESS}
BLOCKCHAIN_LISTENER_BATCH_BLOCKS=${BLOCKCHAIN_LISTENER_BATCH_BLOCKS}
BLOCKCHAIN_STORAGE_PROOF_BATCH_MESSAGES=${BLOCKCHAIN_STORAGE_PROOF_BATCH_MESSAGES}
BLOCKCHAIN_ENYGMA_PROOF_API_ADDRESS="http://circomapi:3000"
BLOCKCHAIN_ENYGMA_PL_EVENTS=${BLOCKCHAIN_ENYGMA_PL_EVENTS}
COMMITCHAIN_CHAINID=${NODE_CC_CHAIN_ID}
COMMITCHAIN_CHAINURL=${RPC_URL_NODE_CC}
COMMITCHAIN_VERSION="2.0"
COMMITCHAIN_CCSTARTINGBLOCK=${COMMITCHAIN_CCSTARTINGBLOCK}
COMMITCHAIN_ATOMICREVERTSTARTINGBLOCK=${COMMITCHAIN_ATOMICREVERTSTARTINGBLOCK}
COMMITCHAIN_OPERATORCHAINID=999
COMMITCHAIN_CCDEPLOYMENTPROXYREGISTRY=${COMMITCHAIN_CCDEPLOYMENTPROXYREGISTRY}
COMMITCHAIN_CCENDPOINTMAXBATCHMESSAGES=500
COMMITCHAIN_EXPIRATIONREVERTTIMEINMINUTES=30
LOG_LEVEL=Info
LOG_HANDLER=Text
KMS_DATABASE_NAME=rayls-kmm
KMS_CORSDOMAIN="*"
KMS_AWSPROFILE="xxx"
KMS_AWSALIAS="xxx"
KMS_GCPPROJECT="xxx"
KMS_GCPLOCATION="xxx"
KMS_GCPKEYRING="xxx"
KMS_GCPCRYPTOKEY="xxx"
KMS_ENCRYPTORSERVICE="plaintext"
BLOCKCHAIN_KMS_API_KEY=${BLOCKCHAIN_KMS_API_KEY}
BLOCKCHAIN_KMS_SECRET=${BLOCKCHAIN_KMS_SECRET}
KMS_DATABASE_CONNECTIONSTRING="mongodb://mongodb:27017/admin?directConnection=true&replicaSet=rs0"
KMS_API_KEY=${KMS_API_KEY}
KMS_SECRET=${KMS_SECRET}
EOF

}

informative_output(){
  echo "Directory created:"
  echo "./rayls/relayer/var"
  echo ""
  
  echo "File created:"
  echo "./rayls/relayer/var/.env"
  echo ""
  echo "Starting Relayer..."  
}

setup_config
informative_output
