apiVersion: apps/v1
kind: Deployment
metadata:
  name: rayls-listener
spec:
  replicas: 1
  selector:                        
    matchLabels:                   
      app: rayls-listener                
  template:
    metadata:
      labels:                      
        app: rayls-listener              
    spec:
     containers:
      - name: rayls-listener
        imagePullPolicy: Always
        image: registry.parfin.io/rayls-listener:v1.8.5
        command: ["./listener","run","--config","/app/var/config.json"]
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: config
          mountPath: "/app/var"
     volumes:
        - name: config
          configMap:
            defaultMode: 0700
            name: rayls-listener
     imagePullSecrets:
     - name: registry-parfin-io