apiVersion: v1
kind: ConfigMap
metadata:
  name: rayls-privacy-ledger
data:
  genesis.json: |
    {
      "config": {
       "chainId": xxxxxxxxxxxxx,
       "homesteadBlock": 0,
       "eip150Block": 0,
       "eip155Block": 0,
       "eip158Block": 0,
       "byzantiumBlock": 0,
       "constantinopleBlock": 0,
       "petersburgBlock": 0,
       "istanbulBlock": 0,
       "berlinBlock": 0,
       "ethash": {}
      },
      "difficulty": "1",
      "gasLimit": "9000000000000",
      "alloc": {
        "0x5f2E7061aDd05c8B4C2b48054E5A591eFFa270Aa": {
          "balance": "300000000000000000000000"
        }
      }
    }
  config.toml: |
    [Eth]
    RPCGasCap = 9000000000000

    [Eth.Ethash]
    DisallowBlockCreation = true
    CacheDir = "ethash"
    CachesInMem = 2
    CachesOnDisk = 3
    CachesLockMmap = false
    DatasetDir = "/app/data/raylz-private-ledger/.ethash"
    DatasetsInMem = 1
    DatasetsOnDisk = 2
    DatasetsLockMmap = false
    PowMode = 0
    NotifyFull = false
  start.sh: |-
    #!/bin/sh

    /app/raylz-private-ledger \
    --http \
    --http.vhosts='*' \
    --http.addr="0.0.0.0" \
    --http.api="net,web3,eth,debug,txpool" \
    --http.port 8545 \
    --http.corsdomain '*' \
    --ipcdisable \
    --ws \
    --ws.addr="0.0.0.0" \
    --ws.port 8660 \
    --ws.api eth,net,web3 \
    --ws.origins '*' \
    --datadir "${DATADIR}" \
    --networkid "${NETWORKID}" \
    --mine \
    --miner.threads=1 \
    --miner.etherbase="${MINER_ETHERBASE}" \
    --metrics \
    --pprof \
    --metrics.addr 0.0.0.0 \
    --metrics.port 6080 \
    --pprof.addr 0.0.0.0  \
    --rpc.gascap 0 \
    --gcmode "archive" \
    --syncmode=full \
    --miner.gasprice 0 \
    --port 30309 \
    --config /app/var/config.toml \
    --db.engine mongodb \
    --db.engine.host "${MONGODB_CONN}" \
    --db.engine.name="${MONGODB_DATABASE}" \
    /app/var/genesis.json