apiVersion: v1
kind: ConfigMap
metadata:
  name: rayls-relayer
data:
  config.json: |
    {
      "Database": {
        "ConnectionString": "mongodb://mongodb:27017/admin?directConnection=true&replicaSet=rs0",
        "Name": "rayls-relayer",
        "Type": "mongodb"
      },
      "Blockchain": {
        "ChainID": "xxxxxxxxxxxx",
        "ChainURL": "http://rayls-privacy-ledger:8545",
        "ChainWSURL": "ws://rayls-privacy-ledger:8660",
        "BatchSize": 1000,
        "StartingBlock": "0"
      },
      "CommitChain": {
        "ChainURL": "xxxxxxxxxxxxx",
        "ChainWSUrl": "xxxxxxxxxxx",
        "CommitChainPLStorageContract": "0x4066b405B6FD10798b7c310C1aa77b351aAC6B8C",
        "ParticipantStorageContract": "0x8863d38A64D5B59F5208b163801e60dEb9eB9AD5",
        "ChainId": "381660001",
        "CcStartingBlock": 5966146,
        "CcAtomicRevertStartingBlock": "5966146",
        "Version": "1.8.6.2",
        "AtomicTeleportContract": "0x27A7DB9E328E68F1ab2cF86Bc803Ee4cF264fffc",
        "ResourceRegistryContract": "0xc44f4350544F3E075b11243fcf83A864d575c0c7",
        "CcEndpointAddress": "0x6928638433Dd9116A4A02b0813E1B19723C9f8F6",
        "BalanceCommitmentContract": "0xC7f7f47800d510B22DB2e9c1e3090c0E4B51Cc30",
        "TokenRegistryContract": "0x06585a6C01f9bcD21dE797479fdCBaFAc6c161b2",
        "OperatorChainId": "999"
      }
    }
